### ISSUE TITLE
Not working with MDX?

### ISSUE THREAD

**Issue by jarodtaylor** [stereobooster/beoe#2]
I want to use this in a Starlight site since the original [rehype-mermaid](https://github.com/remcohaszing/rehype-mermaid) does work in dark mode with SVG. Plus, I love that you have the pan zoom built in.

The problem I'm having is getting it to work in a ` .mdx` file. It works fine in `.md,` but when I use `.mdx,` it doesn't render correctly. It spits in the DOM but doesn't render.

![CleanShot 2024-09-10 at 22 27 29@2x](https://github.com/user-attachments/assets/4a7f6320-a6a5-454d-8503-a5e0486d1c61)

**Comment by stereobooster** [comment]
This can be issue with Astro configuration. There is a [demo in this repository](https://github.com/stereobooster/beoe/blob/main/packages/demo/src/content/docs/examples/mermaid.md) and if I change locally extension to `mdx` - it works

**Comment by jarodtaylor** [comment]
I thought that it may have been the starlight/tailwind template I used, but [this is a fresh install of the base starlight](https://github.com/jarodtaylor/starlight-mermaid), and I only added `@beoe/rehype-mermaid`.

I was following your [directions here](https://astro-digital-garden.stereobooster.com/recipes/mermaid-diagrams-in-markdown/#beoerehype-mermaid) but just had to tweak the custom.css because the SVG was not getting `mermaid` id, so I just changed it to this:

```
html[data-theme="light"] .beoe-dark {
  display: none;
}

html[data-theme="dark"] .beoe-light {
  display: none;
}

.beoe svg {
  /* undo global styles */
  .node .label {
    line-height: 1.2;
  }

  /* primitive dark mode */
  .flowchart-link {
    stroke: var(--sl-color-white) !important;
  }

  .marker {
    stroke: var(--sl-color-white);
    fill: var(--sl-color-white) !important;
  }

  .node-labels {
    fill: var(--sl-color-white);
  }
}
```

Like I said, this works beautifully until I change the file from `.md` to `.mdx`

Do you think it's my astro config or are you thinking it's something with Astro's base config?

**Comment by jarodtaylor** [comment]
BTW, it works fine if I change:

```
rehypePlugins: [
      [
        rehypeMermaid,
        { class: "not-content", strategy: "inline-class-dark-mode" },
      ],
    ],
```
to use `strategy: "img-class-dark-mode"`

It's only doing this on the inline.

**Comment by stereobooster** [comment]
it seems work with

```
@astrojs/starlight 0.22.1
astro 4.7.1
```

but not with latest versions

**Comment by stereobooster** [comment]
I think I found what happened https://github.com/withastro/starlight/releases/tag/%40astrojs%2Fstarlight%400.23.0

> ⚠️ Potentially breaking change: MDX optimization speeds up builds (Starlight’s docs are building ~40% faster for example), but restricts some advanced MDX features. See full details in the [MDX optimization documentation](https://docs.astro.build/en/guides/integrations-guide/mdx/#optimize).

**Comment by jarodtaylor** [comment]
That fixed it! Thank you!

**Comment by stereobooster** [comment]
I will re-open this ticket, because:

> there's a bug in @beoe/rehype-mermaid that is injecting [root hast nodes](https://github.com/syntax-tree/hast?tab=readme-ov-file#root) inside a tree, which is incorrect following the spec:
>
> > Root can be used as the [root](https://github.com/syntax-tree/unist#root) of a [tree](https://github.com/syntax-tree/unist#tree), or as a value of the content field on a 'template' https://github.com/withastro/astro/issues/11971#element, never as a [child](https://github.com/syntax-tree/unist#child).
